CREATE TABLE IF NOT EXISTS b_weather_widget
(
	ID INT NOT NULL AUTO_INCREMENT,
	ACTIVE VARCHAR(1) NOT NULL,
	NAME VARCHAR(100) NULL,
	WIDGET_ID VARCHAR(15) NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS b_weather_widget_option
(
	ID INT NOT NULL AUTO_INCREMENT,
	WIDGET_ID VARCHAR(100) NULL,
	NAME VARCHAR(100) NULL,
	VALUE VARCHAR(200) NULL,
	PRIMARY KEY (ID)
);

INSERT INTO b_weather_widget_option(WIDGET_ID, NAME) VALUES ('w_0', 'weather_provider');

DELIMITER |
CREATE TRIGGER `delete_childs` AFTER DELETE ON `b_weather_widget`
FOR EACH ROW BEGIN
   DELETE FROM b_weather_widget_option WHERE `WIDGET_ID`=OLD.`WIDGET_ID`;
END